/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module spi_control(spi_sclk, rst_n, spi_cs_n, spi_mosi, spi_miso, irq, parallel_key, parallel_data, data_ready, ciphertext_in);
  input spi_sclk;
  wire spi_sclk;
  input rst_n;
  wire rst_n;
  input spi_cs_n;
  wire spi_cs_n;
  input spi_mosi;
  wire spi_mosi;
  output spi_miso;
  reg spi_miso;
  output irq;
  reg irq;
  output [9:0] parallel_key;
  reg [9:0] parallel_key;
  output [7:0] parallel_data;
  reg [7:0] parallel_data;
  output data_ready;
  reg data_ready;
  input [7:0] ciphertext_in;
  wire [7:0] ciphertext_in;
  wire [1:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire [1:0] _023_;
  wire _024_;
  wire [1:0] _025_;
  wire [1:0] _026_;
  wire [1:0] _027_;
  wire [2:0] _028_;
  wire _029_;
  wire _030_;
  wire [1:0] _031_;
  wire [0:0] _032_;
  wire [0:0] _033_;
  wire [7:0] _034_;
  wire [9:0] _035_;
  wire [9:0] _036_;
  wire [1:0] _037_;
  wire [4:0] _038_;
  wire [0:0] _039_;
  wire [0:0] _040_;
  wire [1:0] _041_;
  wire [0:0] _042_;
  wire [0:0] _043_;
  wire [1:0] _044_;
  wire [0:0] _045_;
  wire [0:0] _046_;
  wire [7:0] _047_;
  wire [7:0] _048_;
  wire [1:0] _049_;
  wire [4:0] _050_;
  wire _051_;
  wire _052_;
  reg [4:0] bit_count;
  reg [1:0] current_state;
  reg latch_done;
  wire [1:0] next_state;
  reg [17:0] shift_reg;
  reg [7:0] tx_reg;
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) current_state[0] <= 1'h0;
    else if (_011_) current_state[0] <= next_state[0];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) current_state[1] <= 1'h0;
    else if (_011_) current_state[1] <= next_state[1];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) latch_done <= 1'h0;
    else if (_003_) latch_done <= _032_;
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) data_ready <= 1'h0;
    else if (_005_) data_ready <= _039_;
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) irq <= 1'h0;
    else if (_010_) irq <= _042_;
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[0] <= 1'h0;
    else if (_037_[0]) shift_reg[0] <= spi_mosi;
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[1] <= 1'h0;
    else if (_037_[0]) shift_reg[1] <= shift_reg[0];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[2] <= 1'h0;
    else if (_037_[0]) shift_reg[2] <= shift_reg[1];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[3] <= 1'h0;
    else if (_037_[0]) shift_reg[3] <= shift_reg[2];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[4] <= 1'h0;
    else if (_037_[0]) shift_reg[4] <= shift_reg[3];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[5] <= 1'h0;
    else if (_037_[0]) shift_reg[5] <= shift_reg[4];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[6] <= 1'h0;
    else if (_037_[0]) shift_reg[6] <= shift_reg[5];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[7] <= 1'h0;
    else if (_037_[0]) shift_reg[7] <= shift_reg[6];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[8] <= 1'h0;
    else if (_037_[0]) shift_reg[8] <= shift_reg[7];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[9] <= 1'h0;
    else if (_037_[0]) shift_reg[9] <= shift_reg[8];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[10] <= 1'h0;
    else if (_037_[0]) shift_reg[10] <= shift_reg[9];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[11] <= 1'h0;
    else if (_037_[0]) shift_reg[11] <= shift_reg[10];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[12] <= 1'h0;
    else if (_037_[0]) shift_reg[12] <= shift_reg[11];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[13] <= 1'h0;
    else if (_037_[0]) shift_reg[13] <= shift_reg[12];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[14] <= 1'h0;
    else if (_037_[0]) shift_reg[14] <= shift_reg[13];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[15] <= 1'h0;
    else if (_037_[0]) shift_reg[15] <= shift_reg[14];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[16] <= 1'h0;
    else if (_037_[0]) shift_reg[16] <= shift_reg[15];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[17] <= 1'h0;
    else if (_037_[0]) shift_reg[17] <= shift_reg[16];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) spi_miso <= 1'h0;
    else if (_009_) spi_miso <= _045_;
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) bit_count[0] <= 1'h0;
    else if (_001_) bit_count[0] <= _038_[0];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) bit_count[1] <= 1'h0;
    else if (_001_) bit_count[1] <= _038_[1];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) bit_count[2] <= 1'h0;
    else if (_001_) bit_count[2] <= _038_[2];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) bit_count[3] <= 1'h0;
    else if (_001_) bit_count[3] <= _038_[3];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) bit_count[4] <= 1'h0;
    else if (_001_) bit_count[4] <= _038_[4];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[0] <= 1'h0;
    else if (_040_) parallel_data[0] <= shift_reg[0];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[1] <= 1'h0;
    else if (_040_) parallel_data[1] <= shift_reg[1];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[2] <= 1'h0;
    else if (_040_) parallel_data[2] <= shift_reg[2];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[3] <= 1'h0;
    else if (_040_) parallel_data[3] <= shift_reg[3];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[4] <= 1'h0;
    else if (_040_) parallel_data[4] <= shift_reg[4];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[5] <= 1'h0;
    else if (_040_) parallel_data[5] <= shift_reg[5];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[6] <= 1'h0;
    else if (_040_) parallel_data[6] <= shift_reg[6];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[7] <= 1'h0;
    else if (_040_) parallel_data[7] <= shift_reg[7];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[0] <= 1'h0;
    else if (_040_) parallel_key[0] <= shift_reg[8];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[1] <= 1'h0;
    else if (_040_) parallel_key[1] <= shift_reg[9];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[2] <= 1'h0;
    else if (_040_) parallel_key[2] <= shift_reg[10];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[3] <= 1'h0;
    else if (_040_) parallel_key[3] <= shift_reg[11];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[4] <= 1'h0;
    else if (_040_) parallel_key[4] <= shift_reg[12];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[5] <= 1'h0;
    else if (_040_) parallel_key[5] <= shift_reg[13];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[6] <= 1'h0;
    else if (_040_) parallel_key[6] <= shift_reg[14];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[7] <= 1'h0;
    else if (_040_) parallel_key[7] <= shift_reg[15];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[8] <= 1'h0;
    else if (_040_) parallel_key[8] <= shift_reg[16];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[9] <= 1'h0;
    else if (_040_) parallel_key[9] <= shift_reg[17];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) tx_reg[0] <= 1'h0;
    else if (_033_) tx_reg[0] <= _034_[0];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) tx_reg[1] <= 1'h0;
    else if (_033_) tx_reg[1] <= _034_[1];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) tx_reg[2] <= 1'h0;
    else if (_033_) tx_reg[2] <= _034_[2];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) tx_reg[3] <= 1'h0;
    else if (_033_) tx_reg[3] <= _034_[3];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) tx_reg[4] <= 1'h0;
    else if (_033_) tx_reg[4] <= _034_[4];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) tx_reg[5] <= 1'h0;
    else if (_033_) tx_reg[5] <= _034_[5];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) tx_reg[6] <= 1'h0;
    else if (_033_) tx_reg[6] <= _034_[6];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) tx_reg[7] <= 1'h0;
    else if (_033_) tx_reg[7] <= _034_[7];
  assign _035_[0] = ~bit_count[0];
  assign _012_ = ~current_state[0];
  assign _013_ = ~current_state[1];
  assign _014_ = ~bit_count[1];
  assign _015_ = ~bit_count[4];
  assign _017_ = ~latch_done;
  assign _020_ = ~spi_cs_n;
  assign _036_[0] = _035_[0] & _037_[0];
  assign _036_[1] = _035_[1] & _037_[0];
  assign _036_[2] = _035_[2] & _037_[0];
  assign _036_[3] = _035_[3] & _037_[0];
  assign _036_[4] = _035_[4] & _037_[0];
  assign _043_ = _041_[0] & _033_;
  assign _046_ = _044_[0] & _033_;
  assign _048_[6] = _047_[6] & _031_[1];
  assign _048_[7] = _047_[7] & _031_[1];
  assign _048_[4] = _047_[4] & _037_[0];
  assign _048_[5] = _047_[5] & _037_[0];
  assign _048_[0] = _047_[0] & _033_;
  assign _035_[1] = bit_count[1] ^ bit_count[0];
  assign _035_[2] = bit_count[2] ^ _050_[1];
  assign _035_[3] = bit_count[3] ^ _050_[2];
  assign _035_[4] = bit_count[4] ^ _050_[3];
  assign _050_[2] = bit_count[2] & _050_[1];
  assign _050_[3] = _052_ & _050_[1];
  assign _052_ = bit_count[3] & bit_count[2];
  assign _050_[1] = bit_count[1] & bit_count[0];
  assign _021_ = _008_ & _007_;
  assign _011_ = _021_ & _006_;
  assign _008_ = _020_ | _019_;
  assign _007_ = spi_cs_n | _016_;
  assign _022_ = spi_cs_n | _028_[1];
  assign _006_ = _022_ | _018_;
  assign _010_ = _004_ & _003_;
  assign _004_ = _017_ | _016_;
  assign _009_ = _003_ & _002_;
  assign _003_ = _033_ | _031_[1];
  assign _002_ = latch_done | _016_;
  assign _023_[0] = bit_count[0] | _014_;
  assign _023_[1] = bit_count[2] | bit_count[3];
  assign _024_ = _023_[0] | _023_[1];
  assign _029_ = _024_ | _015_;
  assign _016_ = _012_ | _013_;
  assign _030_ = current_state[0] | _013_;
  assign _018_ = _012_ | current_state[1];
  assign _005_ = _040_ | _031_[1];
  assign _025_[1] = _048_[5] | _048_[7];
  assign _049_[1] = _025_[0] | _025_[1];
  assign _025_[0] = _048_[0] | _040_;
  assign _026_[1] = _048_[4] | _048_[6];
  assign _049_[0] = _025_[0] | _026_[1];
  assign _027_[0] = _033_ | _040_;
  assign _001_ = _037_[0] | _031_[1];
  assign _051_ = _027_[0] | _001_;
  assign _019_ = current_state[0] | current_state[1];
  assign _028_[1] = ~_029_;
  assign _033_ = ~_016_;
  assign _040_ = ~_030_;
  assign _037_[0] = ~_018_;
  assign _031_[1] = ~_019_;
  assign _034_[0] = latch_done ? 1'h0 : ciphertext_in[0];
  assign _034_[1] = latch_done ? tx_reg[0] : ciphertext_in[1];
  assign _034_[2] = latch_done ? tx_reg[1] : ciphertext_in[2];
  assign _034_[3] = latch_done ? tx_reg[2] : ciphertext_in[3];
  assign _034_[4] = latch_done ? tx_reg[3] : ciphertext_in[4];
  assign _034_[5] = latch_done ? tx_reg[4] : ciphertext_in[5];
  assign _034_[6] = latch_done ? tx_reg[5] : ciphertext_in[6];
  assign _034_[7] = latch_done ? tx_reg[6] : ciphertext_in[7];
  assign _041_[0] = latch_done ? 1'hx : 1'h1;
  assign _044_[0] = latch_done ? tx_reg[7] : 1'hx;
  assign _047_[0] = spi_cs_n ? 1'h0 : 1'hx;
  assign _000_[0] = _029_ ? 1'hx : 1'h0;
  assign _000_[1] = _029_ ? 1'hx : 1'h1;
  assign _047_[4] = spi_cs_n ? 1'h0 : _000_[0];
  assign _047_[5] = spi_cs_n ? 1'h0 : _000_[1];
  assign _047_[6] = spi_cs_n ? 1'hx : 1'h1;
  assign _047_[7] = spi_cs_n ? 1'hx : 1'h0;
  assign _032_ = _003_ ? _033_ : 1'hx;
  assign _038_[0] = _001_ ? _036_[0] : 1'hx;
  assign _038_[1] = _001_ ? _036_[1] : 1'hx;
  assign _038_[2] = _001_ ? _036_[2] : 1'hx;
  assign _038_[3] = _001_ ? _036_[3] : 1'hx;
  assign _038_[4] = _001_ ? _036_[4] : 1'hx;
  assign _039_ = _005_ ? _040_ : 1'hx;
  assign _042_ = _003_ ? _043_ : 1'hx;
  assign _045_ = _003_ ? _046_ : 1'hx;
  assign next_state[0] = _051_ ? _049_[0] : 1'hx;
  assign next_state[1] = _051_ ? _049_[1] : 1'hx;
  assign _048_[3:1] = { _040_, _040_, _048_[0] };
  assign _044_[1] = 1'h0;
  assign _047_[3:1] = { 2'h3, _047_[0] };
  assign _026_[0] = _025_[0];
  assign _027_[1] = _001_;
  assign _031_[0] = _033_;
  assign { _028_[2], _028_[0] } = { _018_, spi_cs_n };
  assign _035_[9:5] = 5'h00;
  assign _037_[1] = _031_[1];
  assign _036_[9:5] = 5'h00;
  assign _041_[1] = 1'h0;
  assign _050_[0] = bit_count[0];
endmodule
