/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* src = "sdes/spi_control.v:1.1-101.10" *)
module spi_control(spi_sclk, rst_n, spi_cs_n, spi_mosi, spi_miso, irq, parallel_key, parallel_data, data_ready, ciphertext_in);
  (* src = "sdes/spi_control.v:2.24-2.32" *)
  input spi_sclk;
  wire spi_sclk;
  (* src = "sdes/spi_control.v:3.24-3.29" *)
  input rst_n;
  wire rst_n;
  (* src = "sdes/spi_control.v:4.24-4.32" *)
  input spi_cs_n;
  wire spi_cs_n;
  (* src = "sdes/spi_control.v:5.24-5.32" *)
  input spi_mosi;
  wire spi_mosi;
  (* src = "sdes/spi_control.v:6.24-6.32" *)
  output spi_miso;
  reg spi_miso;
  (* src = "sdes/spi_control.v:7.24-7.27" *)
  output irq;
  reg irq;
  (* src = "sdes/spi_control.v:8.24-8.36" *)
  output [9:0] parallel_key;
  reg [9:0] parallel_key;
  (* src = "sdes/spi_control.v:9.24-9.37" *)
  output [7:0] parallel_data;
  reg [7:0] parallel_data;
  (* src = "sdes/spi_control.v:10.24-10.34" *)
  output data_ready;
  wire data_ready;
  (* src = "sdes/spi_control.v:11.24-11.37" *)
  input [7:0] ciphertext_in;
  wire [7:0] ciphertext_in;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  wire [4:0] _000_;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  wire _001_;
  (* src = "sdes/spi_control.v:87.5-99.8" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  (* src = "sdes/spi_control.v:15.16-15.25" *)
  reg [4:0] bit_count;
  (* src = "sdes/spi_control.v:17.16-17.26" *)
  reg latch_done;
  (* src = "sdes/spi_control.v:14.16-14.25" *)
  reg [17:0] shift_reg;
  (* onehot = 32'd1 *)
  reg [3:0] state;
  (* src = "sdes/spi_control.v:16.16-16.22" *)
  wire [7:0] tx_reg;
  assign _033_ = latch_done ? tx_reg[5] : ciphertext_in[5];
  assign _032_ = latch_done ? tx_reg[4] : ciphertext_in[4];
  assign _031_ = latch_done ? tx_reg[3] : ciphertext_in[3];
  assign _030_ = latch_done ? tx_reg[2] : ciphertext_in[2];
  assign _029_ = latch_done ? tx_reg[1] : ciphertext_in[1];
  assign _028_ = ciphertext_in[0] & ~(latch_done);
  assign _009_ = bit_count[1] & bit_count[0];
  assign _010_ = bit_count[1] | bit_count[0];
  assign _011_ = state[2] & _010_;
  assign _000_[1] = _011_ & ~(_009_);
  assign _012_ = bit_count[2] & _009_;
  assign _013_ = ~(bit_count[3] & _012_);
  assign _014_ = bit_count[3] | _012_;
  assign _015_ = state[2] & _014_;
  assign _000_[3] = _013_ & _015_;
  assign _000_[0] = state[2] & ~(bit_count[0]);
  assign _016_ = bit_count[2] | _009_;
  assign _017_ = state[2] & _016_;
  assign _000_[2] = _017_ & ~(_012_);
  assign _018_ = state[3] | state[0];
  assign _001_ = ~_018_;
  assign _003_ = spi_cs_n & _018_;
  assign _019_ = ~(bit_count[2] | bit_count[3]);
  assign _020_ = bit_count[0] & ~(bit_count[1]);
  assign _021_ = bit_count[4] & _020_;
  assign _022_ = ~(_019_ & _021_);
  assign _023_ = ~(state[2] & _022_);
  assign _024_ = spi_cs_n | ~(state[0]);
  assign _005_ = ~(_023_ & _024_);
  assign _007_ = state[1] | _018_;
  assign _025_ = ~(bit_count[4] ^ _013_);
  assign _000_[4] = state[2] & _025_;
  assign _034_ = latch_done ? tx_reg[6] : ciphertext_in[6];
  assign _004_ = state[2] & ~(_022_);
  assign _008_ = state[2] ? _022_ : state[0];
  assign _026_ = state[3] & ~(spi_cs_n);
  assign _006_ = state[1] | _026_;
  assign _027_ = latch_done ? tx_reg[7] : ciphertext_in[7];
  assign _002_ = state[3] & _027_;
  reg \tx_reg_reg[1] ;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) \tx_reg_reg[1]  <= 1'h0;
    else if (state[3]) \tx_reg_reg[1]  <= _028_;
  assign tx_reg[1] = \tx_reg_reg[1] ;
  reg \tx_reg_reg[2] ;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) \tx_reg_reg[2]  <= 1'h0;
    else if (state[3]) \tx_reg_reg[2]  <= _029_;
  assign tx_reg[2] = \tx_reg_reg[2] ;
  reg \tx_reg_reg[3] ;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) \tx_reg_reg[3]  <= 1'h0;
    else if (state[3]) \tx_reg_reg[3]  <= _030_;
  assign tx_reg[3] = \tx_reg_reg[3] ;
  reg \tx_reg_reg[4] ;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) \tx_reg_reg[4]  <= 1'h0;
    else if (state[3]) \tx_reg_reg[4]  <= _031_;
  assign tx_reg[4] = \tx_reg_reg[4] ;
  reg \tx_reg_reg[5] ;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) \tx_reg_reg[5]  <= 1'h0;
    else if (state[3]) \tx_reg_reg[5]  <= _032_;
  assign tx_reg[5] = \tx_reg_reg[5] ;
  reg \tx_reg_reg[6] ;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) \tx_reg_reg[6]  <= 1'h0;
    else if (state[3]) \tx_reg_reg[6]  <= _033_;
  assign tx_reg[6] = \tx_reg_reg[6] ;
  reg \tx_reg_reg[7] ;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) \tx_reg_reg[7]  <= 1'h0;
    else if (state[3]) \tx_reg_reg[7]  <= _034_;
  assign tx_reg[7] = \tx_reg_reg[7] ;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) irq <= 1'h0;
    else if (_007_) irq <= _001_;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) bit_count[0] <= 1'h0;
    else if (_008_) bit_count[0] <= _000_[0];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) bit_count[1] <= 1'h0;
    else if (_008_) bit_count[1] <= _000_[1];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) bit_count[2] <= 1'h0;
    else if (_008_) bit_count[2] <= _000_[2];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) bit_count[3] <= 1'h0;
    else if (_008_) bit_count[3] <= _000_[3];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) bit_count[4] <= 1'h0;
    else if (_008_) bit_count[4] <= _000_[4];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[0] <= 1'h0;
    else if (state[2]) shift_reg[0] <= spi_mosi;
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[1] <= 1'h0;
    else if (state[2]) shift_reg[1] <= shift_reg[0];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[2] <= 1'h0;
    else if (state[2]) shift_reg[2] <= shift_reg[1];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[3] <= 1'h0;
    else if (state[2]) shift_reg[3] <= shift_reg[2];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[4] <= 1'h0;
    else if (state[2]) shift_reg[4] <= shift_reg[3];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[5] <= 1'h0;
    else if (state[2]) shift_reg[5] <= shift_reg[4];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[6] <= 1'h0;
    else if (state[2]) shift_reg[6] <= shift_reg[5];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[7] <= 1'h0;
    else if (state[2]) shift_reg[7] <= shift_reg[6];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[8] <= 1'h0;
    else if (state[2]) shift_reg[8] <= shift_reg[7];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[9] <= 1'h0;
    else if (state[2]) shift_reg[9] <= shift_reg[8];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[10] <= 1'h0;
    else if (state[2]) shift_reg[10] <= shift_reg[9];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[11] <= 1'h0;
    else if (state[2]) shift_reg[11] <= shift_reg[10];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[12] <= 1'h0;
    else if (state[2]) shift_reg[12] <= shift_reg[11];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[13] <= 1'h0;
    else if (state[2]) shift_reg[13] <= shift_reg[12];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[14] <= 1'h0;
    else if (state[2]) shift_reg[14] <= shift_reg[13];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[15] <= 1'h0;
    else if (state[2]) shift_reg[15] <= shift_reg[14];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[16] <= 1'h0;
    else if (state[2]) shift_reg[16] <= shift_reg[15];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) shift_reg[17] <= 1'h0;
    else if (state[2]) shift_reg[17] <= shift_reg[16];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[0] <= 1'h0;
    else if (state[1]) parallel_data[0] <= shift_reg[0];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[1] <= 1'h0;
    else if (state[1]) parallel_data[1] <= shift_reg[1];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[2] <= 1'h0;
    else if (state[1]) parallel_data[2] <= shift_reg[2];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[3] <= 1'h0;
    else if (state[1]) parallel_data[3] <= shift_reg[3];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[4] <= 1'h0;
    else if (state[1]) parallel_data[4] <= shift_reg[4];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[5] <= 1'h0;
    else if (state[1]) parallel_data[5] <= shift_reg[5];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[6] <= 1'h0;
    else if (state[1]) parallel_data[6] <= shift_reg[6];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_data[7] <= 1'h0;
    else if (state[1]) parallel_data[7] <= shift_reg[7];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) latch_done <= 1'h0;
    else if (_007_) latch_done <= state[3];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[0] <= 1'h0;
    else if (state[1]) parallel_key[0] <= shift_reg[8];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[1] <= 1'h0;
    else if (state[1]) parallel_key[1] <= shift_reg[9];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[2] <= 1'h0;
    else if (state[1]) parallel_key[2] <= shift_reg[10];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[3] <= 1'h0;
    else if (state[1]) parallel_key[3] <= shift_reg[11];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[4] <= 1'h0;
    else if (state[1]) parallel_key[4] <= shift_reg[12];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[5] <= 1'h0;
    else if (state[1]) parallel_key[5] <= shift_reg[13];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[6] <= 1'h0;
    else if (state[1]) parallel_key[6] <= shift_reg[14];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[7] <= 1'h0;
    else if (state[1]) parallel_key[7] <= shift_reg[15];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[8] <= 1'h0;
    else if (state[1]) parallel_key[8] <= shift_reg[16];
  (* src = "sdes/spi_control.v:25.5-84.8" *)
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) parallel_key[9] <= 1'h0;
    else if (state[1]) parallel_key[9] <= shift_reg[17];
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) state[0] <= 1'h1;
    else state[0] <= _003_;
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) state[1] <= 1'h0;
    else state[1] <= _004_;
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) state[2] <= 1'h0;
    else state[2] <= _005_;
  always @(posedge spi_sclk, negedge rst_n)
    if (!rst_n) state[3] <= 1'h0;
    else state[3] <= _006_;
  (* src = "sdes/spi_control.v:87.5-99.8" *)
  always @(negedge spi_sclk, negedge rst_n)
    if (!rst_n) spi_miso <= 1'h0;
    else spi_miso <= _002_;
  assign tx_reg[0] = 1'h0;
  assign data_ready = irq;
endmodule
